config/routes.rb
Rails.application.routes.draw do
  resources :airplanebookings

end

app/models/airplanebooking.rb
class Airplanebooking < ActiveRecord::Base
end

app/controllers/airplanebookings_controller.rb
class AirplanebookingsController < ApplicationController
  before_action :set_airplanebooking, only: [:show, :edit, :update, :destroy]

  # GET /airplanebookings
  # GET /airplanebookings.json
  def index
    @airplanebookings = Airplanebooking.all
  end

  # GET /airplanebookings/1
  # GET /airplanebookings/1.json
  def show
  end

  # GET /airplanebookings/new
  def new
    @airplanebooking = Airplanebooking.new
  end

  # GET /airplanebookings/1/edit
  def edit
  end

  # POST /airplanebookings
  # POST /airplanebookings.json
  def create
    @airplanebooking = Airplanebooking.new(airplanebooking_params)

    respond_to do |format|
      if @airplanebooking.save
        format.html { redirect_to @airplanebooking, notice: 'Airplanebooking was successfully created.' }
        format.json { render :show, status: :created, location: @airplanebooking }
      else
        format.html { render :new }
        format.json { render json: @airplanebooking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airplanebookings/1
  # PATCH/PUT /airplanebookings/1.json
  def update
    respond_to do |format|
      if @airplanebooking.update(airplanebooking_params)
        format.html { redirect_to @airplanebooking, notice: 'Airplanebooking was successfully updated.' }
        format.json { render :show, status: :ok, location: @airplanebooking }
      else
        format.html { render :edit }
        format.json { render json: @airplanebooking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airplanebookings/1
  # DELETE /airplanebookings/1.json
  def destroy
    @airplanebooking.destroy
    respond_to do |format|
      format.html { redirect_to airplanebookings_url, notice: 'Airplanebooking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airplanebooking
      @airplanebooking = Airplanebooking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def airplanebooking_params
      params.require(:airplanebooking).permit(:from, :to, :date_of_journey, :return_date, :noOfPassengers)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/airplanebookings_helper.rb
module AirplanebookingsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/airplanebookings/_form.html.erb
<%= form_for @airplanebooking, :html => { :class => "form-horizontal airplanebooking" } do |f| %>

    <% if @airplanebooking.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@airplanebooking.errors.count, "error") %> prohibited this airplanebooking from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @airplanebooking.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :from, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :from, :class => 'form-control' %>
    </div>
    <%= error_span(@airplanebooking[:from]) %>
  </div>
  <div class="control-group">
    <%= f.label :to, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :to, :class => 'form-control' %>
    </div>
    <%= error_span(@airplanebooking[:to]) %>
  </div>
  <div class="control-group">
    <%= f.label :date_of_journey, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :date_of_journey, :class => 'form-control' %>
    </div>
    <%= error_span(@airplanebooking[:date_of_journey]) %>
  </div>
  <div class="control-group">
    <%= f.label :return_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :return_date, :class => 'form-control' %>
    </div>
    <%= error_span(@airplanebooking[:return_date]) %>
  </div>
  <div class="control-group">
    <%= f.label :noOfPassengers, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :noOfPassengers, :class => 'form-control' %>
    </div>
    <%= error_span(@airplanebooking[:noOfPassengers]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            airplanebookings_path, :class => 'btn btn-default' %>

<% end %>

app/views/airplanebookings/edit.html.erb
<%- model_class = Airplanebooking -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/airplanebookings/index.html.erb
<hr/>

app/views/airplanebookings/indexbackup.html.erb
<%- model_class = Airplanebooking -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:from) %></th>
      <th><%= model_class.human_attribute_name(:to) %></th>
      <th><%= model_class.human_attribute_name(:date_of_journey) %></th>
      <th><%= model_class.human_attribute_name(:return_date) %></th>
      <th><%= model_class.human_attribute_name(:noOfPassengers) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @airplanebookings.each do |airplanebooking| %>
      <tr>
        <td><%= link_to airplanebooking.id, airplanebooking_path(airplanebooking) %></td>
        <td><%= airplanebooking.from %></td>
        <td><%= airplanebooking.to %></td>
        <td><%= airplanebooking.date_of_journey %></td>
        <td><%= airplanebooking.return_date %></td>
        <td><%= airplanebooking.noOfPassengers %></td>
        <td><%=l airplanebooking.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_airplanebooking_path(airplanebooking), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      airplanebooking_path(airplanebooking),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_airplanebooking_path,
            :class => 'btn btn-primary' %>

app/views/airplanebookings/new.html.erb
<%- model_class = Airplanebooking -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/airplanebookings/show.html.erb
<%- model_class = Airplanebooking -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:from) %>:</strong></dt>
  <dd><%= @airplanebooking.from %></dd>
  <dt><strong><%= model_class.human_attribute_name(:to) %>:</strong></dt>
  <dd><%= @airplanebooking.to %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date_of_journey) %>:</strong></dt>
  <dd><%= @airplanebooking.date_of_journey %></dd>
  <dt><strong><%= model_class.human_attribute_name(:return_date) %>:</strong></dt>
  <dd><%= @airplanebooking.return_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:noOfPassengers) %>:</strong></dt>
  <dd><%= @airplanebooking.noOfPassengers %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              airplanebookings_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_airplanebooking_path(@airplanebooking), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              airplanebooking_path(@airplanebooking),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DesignathonChallenge</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>




</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" style="background-color:#2A2925;height:80px" >
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= image_tag 'logo.jpg', :style=>"width:50px;"%></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav">
        <li style="background-color:#ffffff">
     <a  href="#" style="color:#000000">
 <span ><%= image_tag 'plane.png',:style=>"width:50px;"%></span>Flights <span></span></a></li>
 <li>
 	<a href="#" style="color:#ffffff;background-color:#2A2925;height:80px">
 <span ><%= image_tag 'hotel.png', :style=>"width:50px;position:relative;margin-top:-3px;"%></span>Hotels</a></li>
 <li>
 	<a  href="#" style="color:#ffffff;background-color:#2A2925;height:80px">
 <span ><%= image_tag 'taxi.jpg', :style=>"width:50px;"%></span>Car Hire</a></li>
 <li>
 <a  href="#" style="color:#ffffff;background-color:#2A2925;height:80px">
 <span ><%= image_tag 'bus.jpg', :style=>"width:50px;"%></span>Buses</a></li>



    
          
      </ul>
     
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<%= yield %>

</body>
</html>